# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'imessengerApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for imessengerApp
pod 'DuckUI', '~> 0.4.2'
pod 'SwiftyStoreKit', '~> 0.15.0'
pod 'KeychainSwift', '~> 16.0.1'
pod 'Gifu', '~> 3.2.0'


end
